name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2020-11-18
version: '9.0.8'
project: 'drupal'
datestamp: 1605720690
